### ISSUE TITLE
`measure_all` with existing classical register

### ISSUE THREAD

**Issue by MattePalte** [mgrzesiuk/qiskit_utils#1]
# Environment

- **qiskit.__version__**: 0.45.2
- **Python version**: 3.10.12
- **Operating system**: Ubuntu 20.04

# What is happening?
In the Python file [test_parse_counts.py](https://github.com/mgrzesiuk/qiskit_utils/blob/3666b3ea2074ce6ee75fa22a8165880ca147c71d/tst/test_parse_counts.py#L30) the circuit has a `measure_all` that automatically adds a new classical register, then you use `parse_counts` to parse the counts but the newly added classical register.
In this case you do not use the existing register and also add a new one.

# How can we reproduce the issue?
Run the following code in the Python file:

```python
from qiskit import QuantumCircuit, execute, Aer
qc = QuantumCircuit(3, 2)
qc.x(1)
qc.measure_all()
qc.draw()
#               ░ ┌─┐
#    q_0: ──────░─┤M├──────
#         ┌───┐ ░ └╥┘┌─┐
#    q_1: ┤ X ├─░──╫─┤M├───
#         └───┘ ░  ║ └╥┘┌─┐
#    q_2: ──────░──╫──╫─┤M├
#               ░  ║  ║ └╥┘
#    c: 2/═════════╬══╬══╬═
#                  ║  ║  ║
# meas: 3/═════════╩══╩══╩═
#                  0  1  2
```
The circuit has two classical registers, but you only use the new one.

# What should happen?
I would have expected to allocate enough classical bits for the measurements and use the existing classical register.

# Any suggestions?
What about using a larger classical register of size 3 and using the existing one? In this way probably you also do not need the `parse_counts` function anymore.

```python
from qiskit import QuantumCircuit, execute, Aer
qc = QuantumCircuit(3, 3)
qc.x(1)
qc.measure_all(add_bits=False)
qc.draw()
#            ░ ┌─┐
# q_0: ──────░─┤M├──────
#      ┌───┐ ░ └╥┘┌─┐
# q_1: ┤ X ├─░──╫─┤M├───
#      └───┘ ░  ║ └╥┘┌─┐
# q_2: ──────░──╫──╫─┤M├
#            ░  ║  ║ └╥┘
# c: 3/═════════╩══╩══╩═
#               0  1  2
```
Running it would give you the same result, but with a more efficient use of the classical register.

Thanks in advance, I wish you a happy and productive day.

**Comment by mgrzesiuk** [comment]
Hi, [test_parse_counts.py](https://github.com/mgrzesiuk/qiskit_utils/blob/3666b3ea2074ce6ee75fa22a8165880ca147c71d/tst/test_parse_counts.py#L30) is a unit test to verify correctness of parse_counts method, as such using parse_counts is kind of the point (and test it with various combinations of quantum and classical registers)...

this issue does not make much sense in my opinion, as such I am closing it.
